"""
A Flask application to expose the `/process_image` REST API endpoint.

"""

import os
import json
import traceback
from flask import Flask, Response, request

from main import Main
from utils.logger import logger

app = Flask(__name__)
main = Main(base_img_path=os.path.abspath(os.path.join(os.path.abspath(__file__), "../../images")))


@app.route("/process_image", methods=["POST"])
def process_image():
    """
    Exposes image processing functionality. Parameters are to be sent in the request as query params.

    Parameters
    ----------
    session_id : str
        Datetime based unique identifier of the current session. It is generated by the Raspberry Pi and passed
        with the POST request.
    image_name : str
        Name of the image to be processed. The image has to be uploaded to the s3 bucket. Value is passed
        with the POST request.
    arm_id : str
        Unique identifier of the arm, stored in the arm config file.

    """

    try:
        # Retrieve query parameters from the request
        session_id = request.args.get("session_id")
        image_name = request.args.get("image_name")
        arm_id = request.args.get("arm_id")

        # Detect objects on image and save bounding boxes to the database
        main.process_image(arm_id=arm_id, session_id=session_id, image_name=image_name)

        return Response(
            json.dumps({
                "session_id": session_id,
                "image_name": image_name,
                "message": "Image successfully processed!"
            }),
            status=200,
            mimetype='application/json'
        )
    except Exception as e:
        logger.error(e)
        return Response(json.dumps({"result": e}), status=500, mimetype='application/json')


@app.route("/get_commands_of_session", methods=["POST"])
def get_commands_of_session():
    """
    Exposes endpoint to generate commands after all session images has been processed. Parameters are
    to be sent in the request as query params.

    Parameters
    ----------
    session_id : str
        Datetime based unique identifier of the current session. It is generated by the Raspberry Pi and passed
        with the POST request.
    arm_constants : dict
        Arm specific configuration stored in a config yaml file on the Raspberry Pi.
    """

    try:
        # Retrieve parameters from the request
        session_id = request.args.get("session_id")
        arm_constants = request.json

        commands = main.vectorize_session_images(arm_constants=arm_constants, session_id=session_id)

        return Response(json.dumps(commands), status=200, mimetype='application/json')

    except Exception as e:
        traceback.print_exc()
        return Response(json.dumps({"result": e}), status=500, mimetype='application/json')


if __name__ == "__main__":
    app.run(host="0.0.0.0", port=6000, debug=True)
