"""
A Flask application to expose the `/process_image` REST API endpoint.

"""

from main import Main
from flask import Flask, request

app = Flask(__name__)
main = Main()


@app.route("/process_image", methods=["POST"])
def process_image():
    """
    This endpoint exposes image processing functionality.

    Parameters
    ----------
    session_id : str
        Datetime based unique identifier of the current session. It is generated by the Raspberry Pi and passed
        with the POST request.
    image_name : str
        Name of the image to be processed. The image has to be uploaded to the s3 bucket. Value is passed
        with the POST request.
    is_final : bool
        Boolean value indicating if the current image is the last of the session. If it is, all of the session's
        images will be cropped, vectorized and clustered.

    """

    # Retrieve query parameters from the request
    session_id = request.args.get("session_id")
    image_name = request.args.get("image_name")
    is_final = request.args.get("is_final")

    # Detect objects on image and save bounding boxes to the database
    main.process_image(session_id, image_name)

    # If the image is the last of a session, crop and vectorize all objects in current session
    if is_final:
        main.vectorize_session_images()

    return 'ok'


if __name__ == "__main__":
    app.run(host="0.0.0.0", port=6000, debug=True)
