name: SorterBot Cloud

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        lfs: true
        ref: 'tests'
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - uses: actions/cache@v1
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install 'git+https://github.com/cocodataset/cocoapi.git#subdirectory=PythonAPI'
        cd ..
        git clone https://github.com/facebookresearch/detectron2.git
        cd detectron2
        pip install -e .
        cd ../sorterbot_cloud
    - name: Lint with flake8
      run: |
        pip install flake8
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
  # test:
  #   runs-on: ubuntu-latest
  #   steps:
    - name: Unit tests with PyTest
      run: |
        pip install pytest pytest-cov
        export PYTHONPATH=$PYTHONPATH:$(pwd)/src
        pytest tests -v --cov=vectorizer.vectorizer --cov=vectorizer.preprocessor --cov=locator.detectron
